# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D412_mZ5Qf2GwxOIuYRmKgXl6V9dRxL9
"""

import pandas as pd
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
print(df.head())
average_value = df['total_rooms'].mean()
print("Average of the column:", average_value)
summary_stats = df.describe()
print("Summary statistics:\n", summary_stats)
missing_values = df.isnull().sum()
print("Missing values per column:\n",missing_values)